@startuml
'https://plantuml.com/class-diagram

class HeroAircraft {
    - {static} heroAircraft:HeroAircraft
    - HeroAircraft(int locationX, int locationY, double speedX, double speedY, int hp)
    + {static} getHeroAircraft():HeroAircraft
    + increaseHp(int increase):void
    + getLoseHp():int
    + setShootNum(int shootNum):void
    + reset():void
}

HeroAircraft <-- HeroAircraft

@enduml